name: systex_frotas
description: "App Flutter Systex Frotas"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.12.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
